---
name: Push to DEV Cluster
on:
  push:
    branches:
      - production
jobs:
  redeploy_everything:
    name: Deploy Monorepo on DEV Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            
            # Use Node 24
            nvm use 24

            # Verify environment
            node -v
            pnpm -v
            pm2 -v
            
            cd monorepo-deployment
            git pull origin production
            pnpm install
            pnpm run build
            pm2 restart http-backend
            pm2 restart web
            pm2 restart ws-backend